#!/bin/bash

# update repository from current config files or the other way around
# update-repo

SCRIPT_NAME="update-repo"
VERSION="1.0"
OPTS=$(getopt -o fhv \
	--long from \
	--long help \
	--long version \
	-- "$@")

eval set -- "$OPTS"

while true
do
	case "$1" in
		-f|--from)
			FROM=1;;
		-h|--help)
			echo -e "Usage: $SCRIPT_NAME [OPTION]...\n"
			echo -e "Update repository from current config files or the other way around.\n"
			echo "List of possible options:"
			echo -e "\t-f, --from\tcopy from repository to current config files (to repository is default)"
			echo -e "\t-h, --help\tprint this help"
			echo -e "\t-v, --version\tshow version info"
			exit;;
		-v|--version)
			echo "$SCRIPT_NAME (script) $VERSION"
			echo "Written by Hubert Obrzut"
			exit;;
		--) shift; break;;
	esac
	shift
done

dotfiles=(
	bashrc
	vimrc
	xinitrc
	bash_profile
)

for dotfile in "${dotfiles[@]}"; do
	if [ -z "$FROM" ]; then
		cp ~/.$dotfile $dotfile
	else
		mkdir -p backup
		cp ~/.$dotfile backup/$dotfile
		cp $dotfile ~/.$dotfile
	fi
done
