#!/bin/sh

# commands:
	alias sudo='sudo '
	alias pacman='pacman --color=auto'
	alias egrep='egrep --color=auto'
	alias yay='yay --color=auto'
	alias ls='ls -hvN --color=auto --group-directories-first'
	alias grep="grep --color=auto"
	alias igrep="grep -i"
	alias ll='ls --color=always -lAFbhv | less -XER'
	# custom script in which I want to change directory in outer shell (so have to source it)
	alias con=". con"
	alias open='xdg-open'

# shortcuts:
	alias vim="nvim -c 'set scroll=10'"
	alias nvim="nvim -c 'set scroll=10'"
	alias jupyter="run 'jupyter notebook --browser=chromium'"

# custom directories:
	alias misc='cd ~/desktop/misc'
	alias suck="cd ~/desktop/misc/suckless"
	alias codeforces='cd ~/desktop/programs/codeforces'
	alias atcoder='cd ~/desktop/programs/atcoder'
	alias stud='cd $STUD'
	alias scripts='cd ~/.local/bin/scripts'
	alias tutorials='cd ~/desktop/programs/tutorials'
	alias train='cd ~/desktop/programs/contests/misc'
	alias job='cd ~/desktop/misc/job'
	alias current='cd ~/desktop/programs/contests/misc/2020-2021_ACM-ICPC_Brazil_Subregional_Programming_Contest'
	alias cppsrc='cd /usr/include/c++/10.2.0'
	alias ..='cd ../'
	alias ...='cd ../..'
	alias ....='cd ../../..'
	alias .....='cd ../../../..'

# studies:
	# II semester
	alias aisd='cd $STUD/aisd'
	alias mp='cd $STUD/mp'

	# III semester
	alias analn='cd $STUD/analn'
	alias mia='cd $STUD/mia'
	alias pgk='cd $STUD/pgk'
	alias weppo='cd $STUD/weppo'

	# IV semester
	alias ask='cd $STUD/ask'
	alias krypto='cd $STUD/krypto'
	alias linux='cd $STUD/linux'
	alias ppb='cd $STUD/ppb'
	alias si='cd $STUD/si'
	alias sieci='cd $STUD/sieci'

	# V semester
	alias ml='cd $STUD/ml'
	alias so='cd $STUD/so'
	alias ai='cd $STUD/ai4g'
	alias ae='cd $STUD/ae'
	alias c++='cd $STUD/c++stl/tests'
	alias cpptricks='cd $STUD/cpptricks'

	# VI semester
	alias dl='cd $STUD/dl'
	alias poo='cd $STUD/poo'
	alias bazy='cd $STUD/bazy'
	alias jfizo='cd $STUD/jfizo'
	alias poo='cd $STUD/poo'
	alias bazy='cd $STUD/bd'
	alias bachelor='cd $STUD/bachelor'
	alias hyper='cd $STUD/ai4g/project/ai4g-project/hypersonic'
