#!/bin/sh

# specific-regarded aliases

# commands:
    # custom script in which I want to change directory in outer shell (so have to source it)
    alias con=". con"
    alias do-cpp-test=". do-cpp-test"

# shortcuts:
    # custom
    alias suck='cd ~/.local/bin/suckless'
    alias job='cd "$(xdg-user-dir DOCUMENTS)/job"'
    alias codeforces='cd ~/desktop/programs/codeforces'
    alias atcoder='cd ~/desktop/programs/atcoder'
    alias tutorials='cd ~/desktop/programs/tutorials'
    alias train='cd ~/desktop/programs/contests/misc'
    alias stud='cd $STUD'
    alias repos='cd ~/repos'
    alias code='code --disable-web-security'
    alias cudasamples='cd $CUDA_HOME/samples'
    alias coding='cd ~/repos/coding-library'

# studies:
    # I semester
    alias mia='cd $STUD/mia/2018'

    # II semester
    alias aisd='cd $STUD/aisd'
    alias mp='cd $STUD/mp'

    # III semester
    alias analn='cd $STUD/analn'
    alias mia='cd $STUD/mia/2019'
    alias pgk='cd $STUD/pgk'
    alias weppo='cd $STUD/weppo'

    # IV semester
    alias ask='cd $STUD/ask'
    alias krypto='cd $STUD/krypto'
    alias linux='cd $STUD/linux'
    alias ppb='cd $STUD/ppb'
    alias si='cd $STUD/si'
    alias sieci='cd $STUD/sieci'

    # V semester
    alias ml='cd $STUD/ml'
    alias so='cd $STUD/so'
    alias ai='cd $STUD/ai4g'
    alias ae='cd $STUD/ae'
    alias c++='cd $STUD/c++stl/tests'
    alias cpptricks='cd $STUD/cpptricks'

    # VI semester
    alias dl='cd $STUD/dl'
    alias poo='cd $STUD/poo'
    alias bazy='cd $STUD/bazy'
    alias jfizo='cd $STUD/jfizo'
    alias poo='cd $STUD/poo'
    alias bazy='cd $STUD/bazy'
    alias bachelor='cd $STUD/bachelor'

    # VII semester
    alias unity='cd $STUD/unity'
    alias mia='cd $STUD/mia/2021'
    alias cuda='cd $STUD/cuda'
    alias teoarg='cd $STUD/teoarg'

# temporary:
    alias current='cd ~/desktop/programs/contests/cerc/2020/practice'
