#!/bin/sh

# Custom directories:
    export STUD="$HOME/studies"
    export WALLPAPER="$HOME/pictures/wallpaper"
    export CF_DIRECTORY="$HOME/desktop/programs/codeforces" # CodeForces directory
    export ATC_DIRECTORY="$HOME/desktop/programs/atcoder" # AtCoder directory
    export SCRIPTS="$HOME/.local/bin/scripts"
    export SUCK="$HOME/.local/bin/suckless"
    export BACHELOR="$HOME/studies/bachelor"
