#!/bin/sh

# Path:
	export PATH="$PATH:$HOME/.local/bin:$HOME/.local/bin/scripts:$HOME/.local/bin/scripts/cf_submit"

# Default programs:
	export EDITOR="nvim"
	export TERMINAL="st"
	export BROWSER="brave"

# Custom variables:
	export CXXFLAGS="-std=c++17 -Wall -Wextra -ggdb -D LOCAL"
	export CFLAGS="-Wall -Wextra -ggdb"
	export HISTSIZE=2000
	# optout from dotnet data collect
	export DOTNET_CLI_TELEMETRY_OPTOUT=1

# Custom directories:
	export STUD="$HOME/desktop/programs/studies"
	export WALLPAPER="$(xdg-user-dir PICTURES)/wallpaper.jpg"
	export CF_DIRECTORY="$HOME/desktop/programs/codeforces" # CodeForces directory
	export ATC_DIRECTORY="$HOME/desktop/programs/atcoder" # AtCoder directory

# ~/ Clean-up:
	export XDG_CONFIG_HOME="$HOME/.config"
	export XDG_DATA_HOME="$HOME/.local/share"
	export XDG_CACHE_HOME="$HOME/.cache"
	export LESSHISTFILE="-"
	export TEXMFHOME="${XDG_DATA_HOME:-$HOME/.local/share}/texmf"
	export TEXMFVAR="${XDG_CACHE_HOME:-$HOME/.cache}/texlive/texmf-var"
	export TEXMFCONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/texlive/texmf-config"
	export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
	export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"
	export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
	export GNUPGHOME="${XDG_DATA_HOME:-$HOME/.local/share}/gnupg"
	export IPYTHONDIR="${XDG_CONFIG_HOME:-$HOME/.config}/jupyter"
	export JUPYTER_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/jupyter"
	export _JAVA_OPTIONS="${XDG_CONFIG_HOME:-$HOME/.config}/java"
	export NUGET_PACKAGES="${XDG_CACHE_HOME:-$HOME/.cache}/NuGetPackages"
	export VSCODE_PORTABLE="${XDG_DATA_HOME:-$HOME/.local/share}/vscode"
	export DOTNET_CLI_HOME="${XDG_CACHE_HOME:-$HOME/.cache}/dotnetcli"
	export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
	export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
	export PSQLRC="${XDG_CONFIG_HOME:-$HOME/.config}/pg/psqlrc"
	export PSQL_HISTORY="${XDG_CACHE_HOME:-$HOME/.cache}/pg/psql_history"
	export PGPASSFILE="${XDG_CONFIG_HOME:-$HOME/.config}/pg/pgpass"
	export PGSERVICEFILE="${XDG_CONFIG_HOME:-$HOME/.config}/pg/pg_service.conf"
	export PASSWORD_STORE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/pass"
	export NOTMUCH_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/notmuch/notmuchrc"
	export NMBGIT="${XDG_DATA_HOME:-$HOME/local/share}/notmuch/nmbug"
	export MBSYNCRC="${XDG_CONFIG_HOME:-$HOME/.config}/isync/mbsyncrc"
	export ABOOKRC="${XDG_CONFIG_HOME:-$HOME/.config}/abook/abookrc"
	export ABOOKADDRBOOK="${XDG_CONFIG_HOME:-$HOME/.config}/abook/addressbook"
    export SSB_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/zoom"

# automatically "type" startx after login
if systemctl -q is-active graphical.target && [[ ! $DISPLAY && $XDG_VTNR -eq 1 && $USER != root ]]; then
	exec startx "$XINITRC"
fi
