#!/bin/bash

# Disable ctrs-s and ctrl-q stopping terminal
stty -ixon
# Allows you to cd into directory merely by typing the directory name
shopt -s autocd
# complete after custom script 'run'
complete -cf run

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# turn on autocomplete in bash
[ -r /usr/share/bash-completion/bash_completion ] &&
	. /usr/share/bash-completion/bash_completion

# source Git special functions
[ -e /usr/share/git/completion/git-prompt.sh ] &&
	. /usr/share/git/completion/git-prompt.sh

# Load aliases if existent:
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc" ] &&
	. "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc"

# terminal prompt with Git support (show current branch)
PS1="\[\e[31m\][\[\e[m\]\[\e[33m\]\u\[\e[m\]\[\e[32m\]@\[\e[m\]\[\e[34m\]\h\[\e[36m\]\$(__git_ps1 '(%s)')\[\e[35m\] \W\[\e[m\]\[\e[31m\]]\[\e[m\]\\$ "
